qa analysis macros splitting
AliceO2Group/Run3Analysisvalidation pull request #167
Opened 2021-02-24 17:30 UTC by mmazzilli

2021-02-24 18:46 UTC, vkucera requested changes

2021-02-24 18:46 UTC, vkucera commented on FirstAnalysis/HFmcvalidation.py
> +#!/ usr / bin / env python
This doesn't look right.

2021-02-24 18:51 UTC, vkucera requested changes

2021-02-24 18:51 UTC, vkucera commented on FirstAnalysis/HFmcvalidation.py
> +from ROOT import (  # pylint: disable=import-error, no-name-in-module, unused-import; TEfficiency,; TLegend,; gPad,
Why are these checks disabled?

2021-02-25 08:47 UTC, zhangbiao-phy commented on FirstAnalysis/trackingstudies.py
> +specie_distribution("electon", "eta")
replace "electon" to "electron"

2021-02-25 08:48 UTC, zhangbiao-phy commented on FirstAnalysis/trackingstudies.py
> +specie_distribution("electon", "phi")
replace "electon" to "electron"

2021-02-25 09:02 UTC, vkucera commented on FirstAnalysis/HFmcvalidation.py
> +#!/ usr / bin / env python
It's just needed to remove the spaces around slashes. It has to be a valid path.

2021-02-25 09:06 UTC, zhangbiao-phy commented on FirstAnalysis/trackingstudies.py
> +    cvertex_res.Divide(2, 1)
there are only two plots totally, in line 84, the canvas has already be divided into 2.

2021-02-25 09:46 UTC, vkucera commented
@mmazzilli @zhangbiao-phy There seems to be some editing ongoing still. Shall we convert this to a draft until everybody agrees on a final version?

2021-02-25 10:25 UTC, vkucera commented
Merging

2021-02-25 10:26 UTC, merged