add xicc in the flow
AliceO2Group/Run3Analysisvalidation pull request #224
Opened 2021-05-21 19:49 UTC by ginnocen

2021-06-02 20:37 UTC, vkucera requested changes
Shouldn't the other JSON files be updated too?

2021-06-02 20:37 UTC, vkucera commented on codeHF/workflows.yml
> +      mc: "--doMC"
Needless to specify this as it is already inherited from `cand_creator`.

2021-06-02 20:37 UTC, vkucera commented on codeHF/workflows.yml
> +    <<: *selector_2prong
Inheriting from `selector_2prong` seems useless here if all the attributed are overwritten.

2021-06-02 20:41 UTC, vkucera commented on codeHF/config_tasks.sh
> +DOO2_SEL_XICC=0     # hf-xic-topkpipi-candidate-selector
`xic` -> `xicc`

2021-06-02 21:09 UTC, ginnocen commented
thanks a lot @vkucera for the comments.

2021-06-02 22:25 UTC, vkucera commented on codeHF/dpl-config_run5_hf.json
> +    "hf-xicc-topkpipi-candidate-selector": {
This does not seem to match the O2 device name.

2021-08-21 09:34 UTC, vkucera requested changes
Please resolve the conflicts and update the files.

2021-08-21 09:34 UTC, vkucera commented on codeHF/config_input.sh
> +NJOBSPARALLEL_O2=$(python3 -c "print(min(20, round($(nproc) / 2)))")
Please revert unnecessary changes.

2021-08-21 09:34 UTC, vkucera commented on codeHF/config_tasks.sh
> +
Please revert unnecessary changes.

2021-08-21 09:34 UTC, vkucera commented on codeHF/config_tasks.sh
> +    [ $DOO2_TASK_XICC -eq 1 ] && PARTICLES+="-xicc"
The strings now use spaces as separators.

2021-08-21 09:34 UTC, vkucera commented on codeHF/workflows.yml
> +    dependencies: [o2-analysis-hf-xic-topkpi-candidate-selector]
`activate` is obsolete.
Single dependency can be a simple string (instead of a list).

2021-11-02 09:26 UTC, closed without merging