HF correlations continued from the common repo
AliceO2Group/Run3Analysisvalidation pull request #355
Opened 2022-07-29 15:55 UTC by saganatt

Dear all,

this is a continuation of https://github.com/AliceO2Group/Run3Analysisvalidation/pull/349.
The corresponding O2Physics PR is now: https://github.com/AliceO2Group/O2Physics/pull/1084

I am opening a new PR, as this is from a branch in our common repo, so Katarina and Gian can fix potential review comments and errors while I am offline.

2022-08-05 18:34 UTC, vkucera requested changes
- Remove the directory `originals` if not needed.
- Add basic documentation at the top of each .C macro:
  - What it does
  - How to use it
  - Who wrote it

2022-08-06 20:10 UTC, vkucera requested changes
Minor typo correction.

2022-08-06 20:10 UTC, vkucera commented on FirstAnalysis/Correlations/extract2D.C
> +//  Macro to produce 2D histograms of correlations vs. deltahi and deltaeta
```suggestion
//  Macro to produce 2D histograms of correlations vs. delta phi and delta eta
```

2022-08-08 06:45 UTC, saganatt commented on codeHF/config_tasks.sh
> +DOO2_TASK_FLOW=0  # hf-task-correlation-d0
leftover old name

2022-08-08 06:46 UTC, saganatt commented on codeHF/config_tasks.sh
> +  # hf-task-correlation-d0
leftover old name

2022-08-08 07:23 UTC, ginnocen approved these changes

2022-08-08 08:44 UTC, vkucera commented on codeHF/config_input.sh
> +    INPUT_LABEL="Run 2, p-p 13.6 TeV, LHC17j (AO2D)"
```suggestion
    INPUT_LABEL="Run 2, p-p 13 TeV, LHC17j (AO2D)"
```

2022-08-08 08:45 UTC, vkucera approved these changes

2022-08-08 08:50 UTC, merged