PWGHF: Implementing B0 → D- π+ → (π- K+ π-) π+ workflow
AliceO2Group/Run3Analysisvalidation pull request #364
Opened 2022-10-04 12:28 UTC by AlexBigO

Implementation of the B0 workflow along with [this PR](https://github.com/AliceO2Group/O2Physics/pull/1282).

2022-10-05 10:32 UTC, vkucera commented
Hi @AlexBigO , thanks for the PR. I see that the commit called "Clang-formatting" formats the JSON file and changes indentation from 4 spaces (which is the format dumped by O2) to 2 spaces. What tool did you use for the formatting?

2022-10-05 15:10 UTC, AlexBigO commented
Hello again @vkucera . I used `git clang-format` while being in O2.

2022-10-05 19:47 UTC, vkucera commented
> Hello again @vkucera . I used `git clang-format` while being in O2.

But `clang-format` is a C++ formatting tool. It doesn't format JSON.

2022-10-05 20:05 UTC, AlexBigO commented
I just tested it again (by deleting the last commit and clang-formatting) and it is indeed this command that changes the JSON. Indeed, the clang-format is for `.cxx` and I did it automatically (by habit) before opening the PR, I did not know it would change the JSON.
Anyway, I just pushed the same content but without the "Clang-formatting" commit.

2022-10-07 13:16 UTC, vkucera requested changes

2022-10-07 13:16 UTC, vkucera commented on codeHF/dpl-config_run3.json
> +        "magneticField": "20",
Shouldn't this be 5?

2022-10-07 13:16 UTC, vkucera commented on codeHF/dpl-config_run3.json
> +        "d_minrelchi2change": "0.90000000000000002",
Truncate the values with the trailing digits.

2022-10-07 13:16 UTC, vkucera commented on codeHF/dpl-config_run3.json
> +                [
Make this a proper array with rows and columns, as done in other selectors.

2022-10-07 13:16 UTC, vkucera commented on codeHF/dpl-config_run3.json
> +        "selectionFlagB0": "1",
Selection flags should be 0 by default.

2022-10-20 12:22 UTC, vkucera commented on codeHF/dpl-config_run3.json
> +        "cutYCandMax": "0.80",
Why do you cut |y| < 0.8 here but 1.44 in `hf-task-b0`?

2022-10-28 00:29 UTC, vkucera requested changes
Did you try to run with all pieces activated? It seems to me that it cannot run as it is now.

2022-10-28 00:29 UTC, vkucera commented on codeHF/workflows.yml
> +    dependencies: o2-analysis-hf-b0-todpi-candidate-selector
Shouldn't the dependency be the D0 selector?

2022-10-28 00:29 UTC, vkucera commented on codeHF/config_tasks.sh
> +    [ $DOO2_TASK_B0 -eq 1 ] && PARTICLES+=" b0 "
You store the MC histograms in the `b0-mc` directory, not `b0`.

2022-10-29 14:37 UTC, vkucera requested changes

2022-10-29 14:37 UTC, vkucera commented on codeHF/workflows.yml
> +    dependencies: o2-analysis-hf-b0-todpi-candidate-selector
```suggestion
    dependencies: o2-analysis-hf-dplus-topikpi-candidate-selector
```

2022-10-29 14:37 UTC, vkucera commented on codeHF/config_tasks.sh
> +    [ $DOO2_TASK_B0 -eq 1 ] && PARTICLES+=" b0 "
```suggestion
    [ $DOO2_TASK_B0 -eq 1 ] && PARTICLES+=" b0-mc "
```

2022-10-29 14:43 UTC, vkucera approved these changes

2022-10-29 14:47 UTC, merged