D0 selection task
AliceO2Group/Run3Analysisvalidation pull request #38
Opened 2020-09-16 18:40 UTC by nzardosh

2020-09-16 18:42 UTC, nzardosh reviewed
please dont merge yet

2020-09-16 19:09 UTC, vkucera requested changes

2020-09-16 19:09 UTC, vkucera commented on codeHF/runtest.sh
> +  O2EXEC_SEL="o2-analysis-hf-d0-candidate-selector $O2ARGS_SEL"
The `O2ARGS_...` are not defined anywhere.

2020-09-16 19:09 UTC, vkucera commented on codeHF/runtest.sh
> +  O2EXEC_SEL="o2-analysis-hf-d0-candidate-selector $O2ARGS_SEL"
Fix the `O2ARGS` for TOF.

2020-09-17 11:28 UTC, vkucera approved these changes

2020-09-17 12:40 UTC, merged