Add D*
AliceO2Group/Run3Analysisvalidation pull request #427
Opened 2023-11-14 08:04 UTC by fgrosa

2023-11-14 11:07 UTC, vkucera requested changes

2023-11-14 11:07 UTC, vkucera commented on codeHF/dpl-config_run3.json
Please also update the candidate creator.

2023-11-16 10:10 UTC, fgrosa commented on codeHF/dpl-config_run3.json
Thanks for reminding me! Done based on the last implementation in O2Physics (see https://github.com/AliceO2Group/O2Physics/pull/3567)

2024-04-08 16:12 UTC, vkucera approved these changes

2024-04-08 16:13 UTC, merged